server:
  http_listen_port: 9080
  log_level: info

clients:
  - url: http://pi-swarm-loki:3100/loki/api/v1/push

positions:
  filename: /var/lib/promtail/positions.yaml

scrape_configs:
  # Logs du démon Docker (utile pour diagnostiquer)
  - job_name: docker-daemon
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/log/docker.log

  # Tous les conteneurs Docker, avec décodage JSON & labels
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        regex: '/(.*)'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_node_id']
        target_label: 'node_id'
      - source_labels: ['__meta_docker_container_label_traefik_http_routers']
        target_label: 'traefik_router'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_task_name']
        target_label: 'task'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_task_id']
        target_label: 'task_id'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_id']
        target_label: 'service_id'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_node']
        target_label: 'node'
    pipeline_stages:
      - docker: {}
      - cri: {}
      - json:
          expressions:
            level: level
            msg: message
          on_error: drop
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339
          fallback_formats:
            - RFC3339Nano
            - Unix
          action_on_failure: skip