version: "3.8"

networks:
  pi-swarm-traefik-net:
    external: true

services:
  traefik:
    image: traefik:v2.11
    env_file: [ ../env/traefik.env ]
    command:
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --log.level=INFO
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    # ---- Publication des ports : mode "test" (pas de conflit) ou "prod"
    ports:
      # TEST: host 10080->80, 10443->443, 18080->8080
      - target: 80    published: 10080  protocol: tcp   mode: host
      - target: 443   published: 10443  protocol: tcp   mode: host
      - target: 8080  published: 18080  protocol: tcp   mode: host
    # Pour passer en PROD (quand tu couperas l'ancien Traefik):
    #   remplace les 3 lignes ports ci-dessus par:
    #   - target: 80   published: 80   protocol: tcp   mode: host
    #   - target: 443  published: 443  protocol: tcp   mode: host
    #   - target: 8080 published: 8080 protocol: tcp   mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../volumes/traefik/letsencrypt:/letsencrypt
      - ../files/traefik:/dynamic:ro
    networks: [ pi-swarm-traefik-net ]
    deploy:
      placement:
        constraints:
          - node.hostname == pi5-master-01
      labels:
        - traefik.enable=true
        # HTTP -> HTTPS global
        - traefik.http.middlewares.pi-swarm-redirect-to-https.redirectscheme.scheme=https
        - traefik.http.routers.pi-swarm-http-catchall.rule=HostRegexp(`{any:.+}`)
        - traefik.http.routers.pi-swarm-http-catchall.entrypoints=web
        - traefik.http.routers.pi-swarm-http-catchall.middlewares=pi-swarm-redirect-to-https
        # Dashboard
        - traefik.http.routers.pi-swarm-traefik.rule=Host(`${TRAEFIK_DOMAIN}`)
        - traefik.http.routers.pi-swarm-traefik.entrypoints=websecure
        - traefik.http.routers.pi-swarm-traefik.tls=true
        - traefik.http.routers.pi-swarm-traefik.tls.certresolver=le
        - traefik.http.routers.pi-swarm-traefik.service=api@internal