server:
  http_listen_port: 3100
  log_level: info

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# Schéma moderne (boltdb-shipper + filesystem)
schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 5m

table_manager:
  retention_deletes_enabled: true
  retention_period: ${LOKI_RETENTION_DAYS}d

limits_config:
  retention_period: ${LOKI_RETENTION_DAYS}d
  allow_structured_metadata: true

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: ""
  enable_api: true

chunk_store_config:
  max_look_back_period: 0s

query_range:
  parallelise_shardable_queries: true

frontend:
  log_queries_longer_than: 5s